services:

############################
# RADARR
############################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
     - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg 
    volumes:
      - /home/allan/Docker/Radarr/config:/config
      # NFS MOUNTS
      - nas_movies:/movies
      - nas_downloads:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.2
    restart: unless-stopped
    
############################
# SONARR
############################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
     - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /home/allan/Docker/Sonarr/config:/config
      # NFS MOUNTS
      - nas_series:/series
      - nas_downloads:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.3
    restart: unless-stopped
    
############################
# PROWLARR
############################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
     - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /home/allan/Docker/Prowlarr/config:/config
    networks:
      arr_net:
        ipv4_address: 172.28.0.4
    restart: unless-stopped

############################
# BAZARR
############################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports: 
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /home/allan/Docker/Bazarr/config:/config
      # NFS MOUNTS
      - nas_movies:/movies
      - nas_series:/series
    networks:
      arr_net:
        ipv4_address: 172.28.0.5
    restart: unless-stopped
    
############################
# LIDARR
############################
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
     - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /home/allan/Docker/Lidarr/config:/config
      # NFS MOUNTS
      - nas_music:/music
      - nas_downloads:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.6
    restart: unless-stopped

############################
# QBITTORRENT
############################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
     - 8080:8080
     - 6881:6881
     - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/allan/Docker/qbittorrent/config:/config
      # NFS MOUNT
      - nas_downloads:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.7
    restart: unless-stopped
    
############################
# NZBGET
############################
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - NZBGET_USER=nzbget
      - NZBGET_PASS=tegbzn6789
    volumes:
      - /home/allan/Docker/nzbget/config:/config
      # NFS MOUNT
      - nas_downloads:/downloads
    ports:
      - 6789:6789
    networks:
      arr_net:
        ipv4_address: 172.28.0.8
    restart: unless-stopped

############################
# JELLYFIN
############################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /home/allan/Docker/Jellyfin/config:/config
      # NFS MOUNTS
      - nas_series:/series
      - nas_movies:/movies
      - nas_music:/music
      - nas_books:/books
      - nas_pictures:/pictures
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      arr_net:
        ipv4_address: 172.28.0.9
    restart: unless-stopped

############################
# JELLYSEER
############################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - TZ=Africa/Johannesburg
      - LOG_LEVEL=info
    volumes:
      - /home/allan/Docker/jellyseerr/config:/app/config
    networks:
      arr_net:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

############################
# HOMARR (Stable v0.15)
############################
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /home/allan/Docker/Homarr/config:/app/data/configs
      - /home/allan/Docker/Homarr/icons:/app/public/icons
      - /home/allan/Docker/Homarr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Africa/Johannesburg
    ports:
      - 7575:7575
    networks:
      arr_net:
        ipv4_address: 172.28.0.11

############################
# PROFILARR
############################
  profilarr:
    container_name: profilarr
    image: santiagosayshey/profilarr:latest
    restart: unless-stopped
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - /home/allan/Docker/Profilarr/config:/config
    ports:
      - 6868:6868
    networks:
      arr_net:
        ipv4_address: 172.28.0.12

############################
# NETWORK DEFINITION
############################
networks:
  arr_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

############################
# NAS STORAGE (NFS - Synology/QNAP path style)
############################
volumes:
  nas_movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,nolock,soft,rw
      device: ":/volume1/Movies"
  
  nas_series:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,nolock,soft,rw
      device: ":/volume1/Series"

  nas_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,nolock,soft,rw
      device: ":/volume1/Download"

  nas_music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,nolock,soft,rw
      device: ":/volume1/Music"

  nas_books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,nolock,soft,rw
      device: ":/volume1/Books"

  nas_pictures:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.10,nolock,soft,rw
      device: ":/volume1/Pictures"
