---
services:

############################
# RADARR
############################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    #network_mode: "service:gluetun"
    ports:
     - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Radarr/config:/config
      - /share/Movies:/movies #optional
      - /share/Downloads:/downloads #optional
    restart: unless-stopped
    
############################
# SONARR
############################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr
    #network_mode: "service:gluetun"
    ports:
     - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Sonarr/config:/config
      - /share/Series:/tv #optional
      - /share/Downloads:/downloads #optional
    restart: unless-stopped
    
############################
# PROWLARR
############################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    #network_mode: "service:gluetun"
    ports:
     - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Prowlarr/config:/config
    restart: unless-stopped

############################
# BAZARR
############################

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: Bazarr
    ports: 
    - 6767:6767
    #network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Bazarr/config:/config
      - /share/Movies:/movies #optional
      - /share/Series:/tv #optional
    restart: unless-stopped
    
############################
# LIDARR
############################

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: Lidarr
    ports:
     - 8686:8686
    #network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Lidarr/config:/config
      - /share/Music:/music #optional
      - /share/Downloads:/downloads #optional
    restart: unless-stopped
    
############################
# QBITTORRENT		
############################

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: Qbittorrent
    #network_mode: "service:gluetun"
    ports:
     - 8080:8080
     - 6881:6881
     - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /share/Docker/Qbittorrent/config:/config
      - /share/Downloads:/downloads #optional
    restart: unless-stopped
    
############################
# JELLYFIN	
############################

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: Jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Jellyfin/config:/config
      - /share/Series:/data/tvshows
      - /share/Movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

############################
# JELLYSEER
############################
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: Jellyseerr
     ports:
     - 5055:5055
      # network_mode: "service:gluetun"
       environment:
            #- LOG_LEVEL=debug
            - TZ=Africa/Johannesburg          
       volumes:
            - /sjare/Docker/Jellyseer/config:/app/config
       restart: unless-stopped
    
############################
# GLUETUN
############################

#  gluetun:
#    image: qmcgaw/gluetun
#    container_name: Gluetun
#    ports:
#     - 9696:9696 #prowlarr
#     - 7878:7878 #radarr
#      - 8989:8989 #sonarr
#      - 6767:6767 #bazarr
#      - 8686:8686 #lidarr
#      - 8080:8080 #qbittorrent
#      - 6881:6881 #qbittorrent
#      - 6881:6881/udp #qbittorrent
#      - 5055:5055 #jellyseer
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    environment:
#      - VPN_SERVICE_PROVIDER=nordvpn
#      - VPN_TYPE=openvpn # or wireguard
#      - OPENVPN_USER=<your vpn user>
#      - OPENVPN_PASSWORD=<your vpn password>
#      - SERVER_COUNTRIES=South Africa
      
