services:

############################
# RADARR (Direct Network)
############################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    ports:
     - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC 
    volumes:
      - /share/Docker/Radarr/config:/config
      - /share/Movies:/movies
      - /share/Download:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.2
    restart: unless-stopped
    
############################
# SONARR (Direct Network)
############################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr
    ports:
     - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Sonarr/config:/config
      - /share/Series:/data/series
      - /share/Download:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.3
    restart: unless-stopped
    
############################
# PROWLARR (Direct Network)
############################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
     - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Prowlarr/config:/config
    networks:
      arr_net:
        ipv4_address: 172.28.0.4
    restart: unless-stopped

############################
# BAZARR (Direct Network)
############################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: Bazarr
    ports: 
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Bazarr/config:/config
      - /share/Movies:/movies
      - /share/Series:/data/series
    networks:
      arr_net:
        ipv4_address: 172.28.0.5
    restart: unless-stopped
    
############################
# LIDARR (Direct Network)
############################
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: Lidarr
    ports:
     - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Lidarr/config:/config
      - /share/Music:/music
      - /share/Download:/downloads
    networks:
      arr_net:
        ipv4_address: 172.28.0.6
    restart: unless-stopped

############################
# GLUETUN (The VPN Tunnel)
############################
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluetun
    # Gluetun holds the IP for qBittorrent
    networks:
      arr_net:
        ipv4_address: 172.28.0.7
    # Gluetun holds the PORTS for qBittorrent
    ports:
      - 8080:8080         # qBittorrent WebUI
      - 6881:6881         # Torrent TCP
      - 6881:6881/udp     # Torrent UDP
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=YourUserName
      - OPENVPN_PASSWORD=YourPassword
      - SERVER_COUNTRIES=South Africa
    restart: unless-stopped
    
############################
# QBITTORRENT (Behind VPN)		
############################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: Qbittorrent
    # CONNECTS TO GLUETUN ONLY
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /share/Docker/Qbittorrent/config:/config
      - /share/Download:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun

############################
# NZBGET (Direct Network)
############################
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - NZBGET_USER=nzbget
      - NZBGET_PASS=tegbzn6789
    volumes:
      - /share/Docker/nzbget/config:/config
      - /share/Download:/downloads
    ports:
      - 6789:6789
    networks:
      arr_net:
        ipv4_address: 172.28.0.8
    restart: unless-stopped

############################
# JELLYFIN (Direct Network)
############################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: Jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Docker/Jellyfin/config:/config
      - /share/Series:/data/series
      - /share/Movies:/data/movies
      - /share/Music:/data/music
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      arr_net:
        ipv4_address: 172.28.0.9
    restart: unless-stopped

############################
# JELLYSEER (Direct Network)
############################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: Jellyseerr
    ports:
      - 5055:5055
    environment:
      - TZ=Africa/Johannesburg          
    volumes:
      - /share/Docker/Jellyseer/config:/app/config
    networks:
      arr_net:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

############################
# HOMARR (Dashboard)
############################
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /share/Docker/Homarr/configs:/app/data/configs
      - /share/Docker/Homarr/icons:/app/public/icons
      - /share/Docker/Homarr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Africa/Johannesburg
    ports:
      - 7575:7575
    networks:
      arr_net:
        ipv4_address: 172.28.0.11

############################
# PROFILARR (Quality Profiles)
############################
  profilarr:
    container_name: profilarr
    image: santiagosayshey/profilarr:latest
    restart: unless-stopped
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - /share/Docker/Profilarr/config:/config
    ports:
      - 6868:6868
    networks:
      arr_net:
        ipv4_address: 172.28.0.12

############################
# NETWORK DEFINITION
############################
networks:
  arr_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
